name: Deploy to VPS

on:
  push:
    branches:
      - master

# Pekerjaan yang akan dilakukan
jobs:
  deploy:
    # Menjalankan di server virtual Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Masuk ke VPS dan jalankan perintah
      - name: SSH to VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Masuk ke direktori proyek utama di VPS dan tarik perubahan
            cd /home/radens/FinalProject_Docker-Compose && git pull

            # Masuk ke direktori backend dan tarik perubahan
            cd /home/radens/ngobrol_yuk && git pull

            # Masuk ke direktori frontend dan tarik perubahan
            cd /home/radens/nobrolyuk-frontend && git pull

            # Kembali ke direktori utama dan deploy ulang
            cd /home/radens/FinalProject_Docker-Compose
            sudo docker-compose up -d --build